### ISSUE TITLE
The way to generate cfg

### ISSUE THREAD

**Issue by GentleCP** [Yunlongs/Gemini#1]
hello, I wonder could you please provide the code for cfg generating(Gemini). The author of Gemini only provide the nerual network code and the feature files. As far as I know, he use the same feature extractor as the author of Genius used, but the code for generating acfg is incomplete with some important functions missing. 

I have generated the origin binary files by compiling the source code of openssl and do know how to convert these files into feature files(acfgs), could you please help me, appreciate it a lot.

**Comment by YuanBoXie** [comment]
hi, chaopeng. Did you successfully extract ACFG? Could you please give me some tutorials about how to extract ACFG from binaries? I find this [repo](https://github.com/shouguoyang/Gemini) but it has some errors when execute "ida64.exe -A -S.." command：
'{' 不是内部或外部命令，也不是可运行的程序或批处理文件。
