### ISSUE TITLE
the acc and auc values seem abnormal

### ISSUE THREAD

**Issue by zzjss12** [Yunlongs/Gemini#4]
![image](https://user-images.githubusercontent.com/66284098/220820306-a4e661e0-8317-4de9-87ba-8eaf148b745d.png)

**Comment by Yunlongs** [comment]
@zzjss12 I have forgtten the reason, but i will check it soon.

**Comment by zzjss12** [comment]
thanks!

**Comment by Yunlongs** [comment]
@zzjss12  Hi, i have fixed the compution errors. 

 In the before, the lable and similarity are range from [-1,1], but the accuracy and AUC were computed with threshold `0.5` which should be `0`. Now i fixed that error.

**Comment by zzjss12** [comment]
Thanks a lot.
